import { FC, PropsWithChildren } from "react";
import Header from "./header/Header";
import dynamic from "next/dynamic";
import { Props } from "next/script";
import { Metadata, ResolvingMetadata } from "next";
import { IItem, IItemProps } from "@/interfaces/item.interface";

const DynamicFooter = dynamic(() => import("./footer/Footer"), {
  ssr: false,
});
/*
export async function generateMetadata(
  { params, searchParams }: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  console.log(title, description, params);
  return {
    title: "TEST",
  };
}

*/
export const metadata: Metadata = {
  title: "Create APPPPPP",
  description: "Generated by create next app",
};

const Layout: FC<PropsWithChildren<unknown>> = ({ children }) => {
  return (
    <div>
      <Header />
      {children}
      <DynamicFooter />
    </div>
  );
};

export default Layout;
