import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import { nunito } from "@/components/fonts";
import Head from "next/head";
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/


export async function generateMetadata(
  { params, searchParams },
  parent: ResolvingMetadata
): Promise<Metadata> {
  console.log( params);
  return {
    title: "TEST",
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
