import { Metadata } from "next";
import Head from "next/head";
import Image from "next/image";

export const metadata: Metadata = {
    title: "Not found",
    description: "Generated by create next app",
    robots: 'noindex, nofollow',
    openGraph: {
        title: 'Not found'
    },
  };
  

export default function NotFound() {
  return (
    <>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <div className="z-10 max-w-5xl items-center justify-center font-mono text-sm lg:flex">
          <Image
            src="/404.png"
            width={600}
            height={500}
            alt="404 page not found"
          />
        </div>
      </main>
    </>
  );
}
